/**
 * REAL NTRU TRAPDOOR SIGNING, at a toy dimension.
 *
 * Panels 2 and 3 run `signFalconIllustrative`, which — as its own doc comment
 * says at length — never reads the private key. The page is honest about that,
 * but honesty about a missing mechanism is not the mechanism. This module
 * supplies it: a signature that genuinely cannot be produced without the
 * trapdoor, and that stops verifying the moment the trapdoor is damaged.
 *
 * WHAT IS REAL HERE
 *  - The full NTRU trapdoor basis. `generateTrapdoorKey` samples (f, g) from
 *    Falcon's own key distribution (σ = 1.17·√(q/2n)) and then SOLVES the NTRU
 *    equation f·G − g·F = q for the completion (F, G), exactly, in BigInt
 *    arithmetic, via resultants and the extended Euclidean algorithm. The
 *    equation is then re-checked coefficient by coefficient; a key whose
 *    equation does not hold is discarded, never displayed.
 *  - Signing. The signature is Babai round-off against the 2n-dimensional
 *    lattice generated by the rotations of (g, −f) and (G, −F). Without (F, G)
 *    that basis has rank n, not 2n, and the algorithm has nothing to round
 *    against — which is exactly why this signer depends on the private key and
 *    the illustrative one does not.
 *  - Verification. Falcon's real equation: s₁ + s₂·h ≡ c (mod q), plus the norm
 *    bound ‖(s₁, s₂)‖² ≤ β². The verifier touches nothing but h, the message,
 *    the nonce and the signature.
 *  - The forgery. `forgeWithoutTrapdoor` satisfies the verification EQUATION
 *    perfectly — anyone can, by picking s₂ freely and setting s₁ = c − s₂·h —
 *    and fails the norm check by orders of magnitude, because finding a SHORT
 *    solution is the lattice problem the trapdoor solves and nothing else does.
 *
 * WHAT IS NOT REAL, AND SAID SO ON THE PAGE
 *  - n = 8, not 512 or 1024. A real NTRU lattice is 1024- or 2048-dimensional;
 *    this one is 16-dimensional and offers no security whatsoever. Its basis
 *    could be reduced to a trapdoor by LLL in milliseconds. It is a mechanism
 *    exhibit, not a cipher.
 *  - Babai ROUND-OFF, not Falcon's fast-Fourier Gaussian sampler. Round-off is
 *    the NTRUSign approach, and it leaks: every signature is a point in the
 *    fundamental parallelepiped of the secret basis, so a few thousand
 *    signatures recover the private key (Nguyen–Regev 2006). Falcon replaces it
 *    with discrete Gaussian sampling for precisely that reason. This is the
 *    single most important thing the exhibit is NOT showing, and the panel says
 *    so beside the signature.
 *  - The Babai coefficients are solved in float64 rather than exact rationals.
 *    This cannot affect correctness — ANY integer coefficient vector yields a
 *    valid coset representative, so the verification equation holds regardless;
 *    rounding error can only make ‖s‖ slightly longer, and ‖s‖ is measured
 *    exactly in BigInt afterwards.
 */

const enc = new TextEncoder();

export const TOY_N = 8;
export const TOY_Q = 12289; // Falcon's own modulus, kept for recognisability
/** Falcon's key-generation σ, evaluated at this toy n. */
export const TOY_SIGMA = 1.17 * Math.sqrt(TOY_Q / (2 * TOY_N));

/**
 * Acceptance bound β² for this toy scheme.
 *
 * DEMO CONSTANT, calibrated over 300 keys × 200 signatures (60,000 samples): the
 * measured ‖s‖² distribution has min ≈2,400, median ≈27,200, p90 ≈49,100 and
 * max ≈456,000, and 80.4% of honest signatures land at or below 40,000 — so the
 * rejection loop stays visible at one to two attempts, which is why the bound is
 * here rather than at the distribution's tail. `tests/trapdoor.test.ts`
 * re-derives the acceptance rate on every run and fails if it drifts out of
 * band, so this comment cannot go stale silently. A forger without the
 * trapdoor lands around 1.1 × 10⁸ — about 2,750× over this bound — so the
 * separation the bound is doing real work on is four orders of magnitude wide,
 * not a knife edge. Falcon-512's actual ⌊β²⌋ is 34,034,726, for a lattice
 * 64 times larger in dimension; the two numbers are not comparable and the page
 * does not compare them.
 */
export const TOY_BOUND_SQ = 40000n;

/** Falcon retries with a fresh nonce when a signature comes out too long. */
const MAX_SIGN_ATTEMPTS = 16;

// ── polynomial arithmetic in Z[x]/(xⁿ+1) ───────────────────────────────────

export function negacyclicMul(a: bigint[], b: bigint[], n: number): bigint[] {
  const out = new Array<bigint>(n).fill(0n);
  for (let i = 0; i < n; i += 1) {
    for (let j = 0; j < n; j += 1) {
      const k = i + j;
      if (k < n) out[k] += a[i] * b[j];
      else out[k - n] -= a[i] * b[j];
    }
  }
  return out;
}

function rotate(a: bigint[], i: number, n: number): bigint[] {
  const e = new Array<bigint>(n).fill(0n);
  e[i] = 1n;
  return negacyclicMul(a, e, n);
}

function multiplicationMatrix(a: bigint[], n: number): bigint[][] {
  const cols: bigint[][] = [];
  for (let j = 0; j < n; j += 1) cols.push(rotate(a, j, n));
  return Array.from({ length: n }, (_, i) => cols.map((c) => c[i]));
}

export function normSq(v: bigint[]): bigint {
  return v.reduce((s, x) => s + x * x, 0n);
}

// ── exact rational linear algebra (BigInt fractions) ────────────────────────

type Frac = [bigint, bigint];

function bgcd(a: bigint, b: bigint): bigint {
  let x = a < 0n ? -a : a;
  let y = b < 0n ? -b : b;
  while (y) {
    const t = x % y;
    x = y;
    y = t;
  }
  return x;
}

function fnorm([nu, de]: Frac): Frac {
  let n = nu;
  let d = de;
  if (d < 0n) {
    n = -n;
    d = -d;
  }
  const g = bgcd(n, d) || 1n;
  return [n / g, d / g];
}

const fsub = (a: Frac, b: Frac): Frac => fnorm([a[0] * b[1] - b[0] * a[1], a[1] * b[1]]);
const fmul = (a: Frac, b: Frac): Frac => fnorm([a[0] * b[0], a[1] * b[1]]);
const fdiv = (a: Frac, b: Frac): Frac => fnorm([a[0] * b[1], a[1] * b[0]]);

/** Exact Gauss–Jordan over Q. Returns null when the matrix is singular. */
function solveExact(A: bigint[][], b: bigint[]): Frac[] | null {
  const n = b.length;
  const M: Frac[][] = A.map((row, i) => [...row.map((v): Frac => [v, 1n]), [b[i], 1n] as Frac]);
  for (let col = 0; col < n; col += 1) {
    let piv = -1;
    for (let r = col; r < n; r += 1) {
      if (M[r][col][0] !== 0n) {
        piv = r;
        break;
      }
    }
    if (piv === -1) return null;
    [M[col], M[piv]] = [M[piv], M[col]];
    const p = M[col][col];
    for (let c = col; c <= n; c += 1) M[col][c] = fdiv(M[col][c], p);
    for (let r = 0; r < n; r += 1) {
      if (r === col || M[r][col][0] === 0n) continue;
      const factor = M[r][col];
      for (let c = col; c <= n; c += 1) M[r][c] = fsub(M[r][c], fmul(factor, M[col][c]));
    }
  }
  return M.map((row) => row[n]);
}

/** Bareiss fraction-free determinant — the resultant Res(a, xⁿ+1). */
function determinant(M: bigint[][]): bigint {
  const n = M.length;
  const A = M.map((r) => [...r]);
  let prev = 1n;
  let sign = 1n;
  for (let k = 0; k < n - 1; k += 1) {
    if (A[k][k] === 0n) {
      let sw = -1;
      for (let r = k + 1; r < n; r += 1) {
        if (A[r][k] !== 0n) {
          sw = r;
          break;
        }
      }
      if (sw === -1) return 0n;
      [A[k], A[sw]] = [A[sw], A[k]];
      sign = -sign;
    }
    for (let i = k + 1; i < n; i += 1) {
      for (let j = k + 1; j < n; j += 1) {
        A[i][j] = (A[i][j] * A[k][k] - A[i][k] * A[k][j]) / prev;
      }
    }
    prev = A[k][k];
  }
  return sign * A[n - 1][n - 1];
}

function extendedGcd(a: bigint, b: bigint): [bigint, bigint, bigint] {
  if (b === 0n) return [a, 1n, 0n];
  const [g, x, y] = extendedGcd(b, a % b);
  return [g, y, x - (a / b) * y];
}

/** The adjugate a-star, with a·a-star = Res(a) ∈ Z; over Q the inverse of a is
 *  a-star divided by Res(a). */
function adjugate(a: bigint[], n: number): { adj: bigint[]; res: bigint } | null {
  const M = multiplicationMatrix(a, n);
  const res = determinant(M);
  if (res === 0n) return null;
  const sol = solveExact(M, [res, ...new Array<bigint>(n - 1).fill(0n)]);
  if (!sol || sol.some((s) => s[1] !== 1n)) return null;
  return { adj: sol.map((s) => s[0]), res };
}

// ── key generation: solve f·G − g·F = q ─────────────────────────────────────

export type TrapdoorKeyPair = {
  n: number;
  q: number;
  f: bigint[];
  g: bigint[];
  F: bigint[];
  G: bigint[];
  /** Public key h = g·f⁻¹ mod q, coefficients in [0, q). */
  h: number[];
  /** (f, g) draws needed before the NTRU equation was solvable. */
  keygenAttempts: number;
  /** f·G − g·F, evaluated exactly. Must equal q + 0x + 0x² + … */
  equationLhs: bigint[];
  equationHolds: boolean;
  shortBasisNormSq: bigint;
  completionNormSq: bigint;
};

function gaussianInt(sigma: number): bigint {
  const r = new Uint32Array(2);
  crypto.getRandomValues(r);
  const u1 = Math.max(r[0] / 0x1_0000_0000, 1e-12);
  const u2 = r[1] / 0x1_0000_0000;
  return BigInt(Math.round(Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2) * sigma));
}

/** Modular inverse of a polynomial mod q, by Gauss–Jordan over GF(q). */
function polyInverseModQ(a: bigint[], n: number, q: number): number[] | null {
  const M = multiplicationMatrix(a, n).map((row) =>
    row.map((v) => Number(((v % BigInt(q)) + BigInt(q)) % BigInt(q)))
  );
  const A = M.map((row, i) => [...row, i === 0 ? 1 : 0]);
  const inv = (x: number): number => {
    let result = 1;
    let base = x % q;
    let e = q - 2;
    while (e > 0) {
      if (e & 1) result = (result * base) % q;
      base = (base * base) % q;
      e >>= 1;
    }
    return result;
  };
  for (let col = 0; col < n; col += 1) {
    let piv = -1;
    for (let r = col; r < n; r += 1) {
      if (A[r][col] % q !== 0) {
        piv = r;
        break;
      }
    }
    if (piv === -1) return null;
    [A[col], A[piv]] = [A[piv], A[col]];
    const ip = inv(A[col][col]);
    for (let c = col; c <= n; c += 1) A[col][c] = (A[col][c] * ip) % q;
    for (let r = 0; r < n; r += 1) {
      if (r === col || A[r][col] === 0) continue;
      const factor = A[r][col];
      for (let c = col; c <= n; c += 1) A[r][c] = ((A[r][c] - factor * A[col][c]) % q + q) % q;
    }
  }
  return A.map((r) => r[n]);
}

/** Shorten (F, G) by subtracting integer multiples of the rotations of (f, g).
 *  The NTRU equation is invariant under this: f·(G+kg) − g·(F+kf) = f·G − g·F. */
function sizeReduce(f: bigint[], g: bigint[], F: bigint[], G: bigint[], n: number): { F: bigint[]; G: bigint[] } {
  const rows: bigint[][] = [];
  for (let i = 0; i < n; i += 1) rows.push([...rotate(f, i, n), ...rotate(g, i, n)]);
  let w = [...F, ...G];
  for (let iter = 0; iter < 6; iter += 1) {
    const gram = rows.map((r1) => rows.map((r2) => r1.reduce((s, v, k) => s + v * r2[k], 0n)));
    const rhs = rows.map((r) => r.reduce((s, v, k) => s + v * w[k], 0n));
    const mu = solveExact(gram, rhs);
    if (!mu) break;
    const k = mu.map(roundFrac);
    if (k.every((x) => x === 0n)) break;
    for (let i = 0; i < n; i += 1) {
      for (let j = 0; j < 2 * n; j += 1) w[j] -= k[i] * rows[i][j];
    }
  }
  return { F: w.slice(0, n), G: w.slice(n) };
}

function roundFrac([nu, de]: Frac): bigint {
  const half = de / 2n;
  let quotient = nu / de;
  const rem = nu - quotient * de;
  if (rem > half) quotient += 1n;
  else if (-rem > half) quotient -= 1n;
  return quotient;
}

export function ntruEquationLhs(key: Pick<TrapdoorKeyPair, 'f' | 'g' | 'F' | 'G' | 'n'>): bigint[] {
  const fg = negacyclicMul(key.f, key.G, key.n);
  const gf = negacyclicMul(key.g, key.F, key.n);
  return fg.map((v, i) => v - gf[i]);
}

export function equationHolds(lhs: bigint[], q: number): boolean {
  return lhs[0] === BigInt(q) && lhs.slice(1).every((v) => v === 0n);
}

export function generateTrapdoorKey(n = TOY_N, q = TOY_Q, sigma = TOY_SIGMA): TrapdoorKeyPair {
  for (let attempt = 1; attempt <= 200; attempt += 1) {
    const f = Array.from({ length: n }, () => gaussianInt(sigma));
    const g = Array.from({ length: n }, () => gaussianInt(sigma));

    const af = adjugate(f, n);
    const ag = adjugate(g, n);
    if (!af || !ag) continue;

    // u·Res(f) + v·Res(g) = 1  ⇒  F = −q·v·g*, G = q·u·f*  solves f·G − g·F = q.
    const absF = af.res < 0n ? -af.res : af.res;
    const absG = ag.res < 0n ? -ag.res : ag.res;
    const [gcd, u0, v0] = extendedGcd(absF, absG);
    if (gcd !== 1n) continue;
    const u = af.res < 0n ? -u0 : u0;
    const v = ag.res < 0n ? -v0 : v0;

    const rawG = af.adj.map((c) => BigInt(q) * u * c);
    const rawF = ag.adj.map((c) => -BigInt(q) * v * c);
    const { F, G } = sizeReduce(f, g, rawF, rawG, n);

    const lhs = ntruEquationLhs({ f, g, F, G, n });
    if (!equationHolds(lhs, q)) continue;

    const h = polyInverseModQ(f, n, q);
    if (!h) continue;
    const hPoly = negacyclicMul(g, h.map(BigInt), n).map((val) =>
      Number(((val % BigInt(q)) + BigInt(q)) % BigInt(q))
    );

    return {
      n,
      q,
      f,
      g,
      F,
      G,
      h: hPoly,
      keygenAttempts: attempt,
      equationLhs: lhs,
      equationHolds: true,
      shortBasisNormSq: normSq([...g, ...f.map((x) => -x)]),
      completionNormSq: normSq([...G, ...F.map((x) => -x)])
    };
  }
  throw new Error('Could not solve the NTRU equation in 200 draws (expected ~2).');
}

// ── the lattice basis and Babai round-off ──────────────────────────────────

/** Rows of the trapdoor basis: rotations of (g, −f), then of (G, −F). */
export function trapdoorBasis(key: TrapdoorKeyPair): bigint[][] {
  const { n } = key;
  const rows: bigint[][] = [];
  for (let i = 0; i < n; i += 1) rows.push([...rotate(key.g, i, n), ...rotate(key.f, i, n).map((x) => -x)]);
  for (let i = 0; i < n; i += 1) rows.push([...rotate(key.G, i, n), ...rotate(key.F, i, n).map((x) => -x)]);
  return rows;
}

function solveFloat(A: number[][], b: number[]): number[] | null {
  const n = b.length;
  const M = A.map((r, i) => [...r, b[i]]);
  for (let col = 0; col < n; col += 1) {
    let piv = col;
    for (let r = col; r < n; r += 1) if (Math.abs(M[r][col]) > Math.abs(M[piv][col])) piv = r;
    [M[col], M[piv]] = [M[piv], M[col]];
    const p = M[col][col];
    if (p === 0 || !Number.isFinite(p)) return null;
    for (let c = col; c <= n; c += 1) M[col][c] /= p;
    for (let r = 0; r < n; r += 1) {
      if (r === col) continue;
      const factor = M[r][col];
      if (factor === 0) continue;
      for (let c = col; c <= n; c += 1) M[r][c] -= factor * M[col][c];
    }
  }
  return M.map((r) => r[n]);
}

/**
 * Babai round-off against `rows`: find a lattice point near (c, 0) and return
 * the difference. Any integer coefficient vector produces a valid answer, so
 * the float solve below cannot make the result INCORRECT — only longer.
 */
function roundOff(rows: bigint[][], c: number[], n: number): bigint[] | null {
  const t = [...c.map(BigInt), ...new Array<bigint>(n).fill(0n)];
  const gram = rows.map((r1) => rows.map((r2) => Number(r1.reduce((s, v, k) => s + v * r2[k], 0n))));
  const rhs = rows.map((r) => Number(r.reduce((s, v, k) => s + v * t[k], 0n)));
  const mu = solveFloat(gram, rhs);
  if (!mu || mu.some((x) => !Number.isFinite(x))) return null;
  const k = mu.map((x) => BigInt(Math.round(x)));
  const s = [...t];
  for (let i = 0; i < rows.length; i += 1) {
    for (let j = 0; j < 2 * n; j += 1) s[j] -= k[i] * rows[i][j];
  }
  return s;
}

// ── the challenge, hashed from the message ─────────────────────────────────

function bytesToHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

export function randomNonceHex(): string {
  const nonce = new Uint8Array(16);
  crypto.getRandomValues(nonce);
  return bytesToHex(nonce);
}

/** c = H(message ‖ nonce ‖ h) expanded to n coefficients mod q. */
export async function challengeFor(
  message: string,
  nonceHex: string,
  h: number[],
  n: number,
  q: number
): Promise<number[]> {
  const hBytes = new Uint8Array(h.length * 2);
  const view = new DataView(hBytes.buffer);
  for (let i = 0; i < h.length; i += 1) view.setUint16(i * 2, h[i], true);
  const msg = enc.encode(message);
  const nonce = hexToBytes(nonceHex);
  const input = new Uint8Array(msg.length + nonce.length + hBytes.length);
  input.set(msg, 0);
  input.set(nonce, msg.length);
  input.set(hBytes, msg.length + nonce.length);

  const out: number[] = [];
  let counter = 0;
  while (out.length < n) {
    const block = new Uint8Array(
      await crypto.subtle.digest('SHA-256', new Uint8Array([...input, counter]) as ArrayBufferView<ArrayBuffer>)
    );
    for (let i = 0; i + 1 < block.length && out.length < n; i += 2) {
      out.push(((block[i] << 8) | block[i + 1]) % q);
    }
    counter += 1;
  }
  return out;
}

// ── signing, verification, forgery ─────────────────────────────────────────

export type TrapdoorSignature = {
  n: number;
  q: number;
  nonceHex: string;
  s1: bigint[];
  s2: bigint[];
  normSq: bigint;
};

export type SignAttemptRecord = {
  attempt: number;
  nonceHex: string;
  normSq: bigint;
  accepted: boolean;
};

export type TrapdoorSignResult = {
  signature: TrapdoorSignature | null;
  attempts: SignAttemptRecord[];
  bound: bigint;
  /** How many basis rows the signer had. 2n with the trapdoor, n without. */
  basisRows: number;
  /** basisRows === 2n: the basis spans the whole lattice. */
  spansLattice: boolean;
  /** Shortest vector any attempt produced, even when all were rejected. */
  bestNormSq: bigint | null;
};

/**
 * Sign with the trapdoor.
 *
 * The private key is load-bearing, and the exhibit shows exactly how. (F, G)
 * supply n of the 2n basis rows. Handed only the (f, g) half — see
 * `strippedBasis` — round-off still runs and still lands in the right coset, so
 * the verification EQUATION keeps holding; what it cannot do is cancel the
 * target's components in the n directions the missing rows span, so every
 * result comes out roughly q/2 away there and the norm check rejects all of
 * them. The measured norms of those rejected attempts are returned so the page
 * can put them next to the forger's, which is where they belong: a signer
 * holding half the private key is no better off than someone holding none of it.
 */
export async function signWithTrapdoor(
  key: TrapdoorKeyPair,
  message: string,
  rows = trapdoorBasis(key)
): Promise<TrapdoorSignResult> {
  const attempts: SignAttemptRecord[] = [];
  const spansLattice = rows.length === 2 * key.n;
  let bestNormSq: bigint | null = null;
  for (let attempt = 1; attempt <= MAX_SIGN_ATTEMPTS; attempt += 1) {
    const nonceHex = randomNonceHex();
    const c = await challengeFor(message, nonceHex, key.h, key.n, key.q);
    const s = roundOff(rows, c, key.n);
    if (!s) break;
    const n2 = normSq(s);
    if (bestNormSq === null || n2 < bestNormSq) bestNormSq = n2;
    const accepted = n2 <= TOY_BOUND_SQ;
    attempts.push({ attempt, nonceHex, normSq: n2, accepted });
    if (accepted) {
      return {
        signature: { n: key.n, q: key.q, nonceHex, s1: s.slice(0, key.n), s2: s.slice(key.n), normSq: n2 },
        attempts,
        bound: TOY_BOUND_SQ,
        basisRows: rows.length,
        spansLattice,
        bestNormSq
      };
    }
  }
  return { signature: null, attempts, bound: TOY_BOUND_SQ, basisRows: rows.length, spansLattice, bestNormSq };
}

/** The rank-n basis a signer holding only (f, g) would have. */
export function strippedBasis(key: TrapdoorKeyPair): bigint[][] {
  return trapdoorBasis(key).slice(0, key.n);
}

export type TrapdoorVerifyResult = {
  /** s₁ + s₂·h ≡ c (mod q) — Falcon's verification equation. */
  equationOk: boolean;
  normOk: boolean;
  overall: boolean;
  normSq: bigint;
  bound: bigint;
  /** Coefficients where the equation failed, for display. */
  mismatches: number;
};

export async function verifyTrapdoor(
  h: number[],
  message: string,
  signature: TrapdoorSignature
): Promise<TrapdoorVerifyResult> {
  const { n, q } = signature;
  const c = await challengeFor(message, signature.nonceHex, h, n, q);
  const s2h = negacyclicMul(signature.s2, h.map(BigInt), n);
  const Q = BigInt(q);
  let mismatches = 0;
  for (let i = 0; i < n; i += 1) {
    const lhs = (((s2h[i] + signature.s1[i]) % Q) + Q) % Q;
    if (lhs !== BigInt(c[i] % q)) mismatches += 1;
  }
  const measured = normSq([...signature.s1, ...signature.s2]);
  const equationOk = mismatches === 0;
  const normOk = measured <= TOY_BOUND_SQ;
  return {
    equationOk,
    normOk,
    overall: equationOk && normOk,
    normSq: measured,
    bound: TOY_BOUND_SQ,
    mismatches
  };
}

export type ForgeResult = {
  signature: TrapdoorSignature;
  tries: number;
  bestNormSq: bigint;
  bound: bigint;
};

/**
 * Forge without the trapdoor. The forger can always satisfy the EQUATION —
 * choose s₂ freely, set s₁ = c − s₂·h (mod q), centred — and the verifier's
 * equation check will pass every time. What the forger cannot do is make the
 * result short: s₁ comes out uniform over the whole of [−q/2, q/2), so ‖s‖²
 * lands near n·q²/12 per half. Trying repeatedly and keeping the best barely
 * helps, which is the point; the search space is the lattice problem.
 */
export async function forgeWithoutTrapdoor(
  h: number[],
  message: string,
  n: number,
  q: number,
  tries = 200
): Promise<ForgeResult> {
  const Q = BigInt(q);
  const half = Q / 2n;
  let best: TrapdoorSignature | null = null;
  for (let t = 0; t < tries; t += 1) {
    const nonceHex = randomNonceHex();
    const c = await challengeFor(message, nonceHex, h, n, q);
    const raw = new Uint16Array(n);
    crypto.getRandomValues(raw);
    // A forger who is trying hard keeps s₂ small; it does not save them,
    // because s₁ is then forced to be uniform.
    const s2 = Array.from({ length: n }, (_, i) => BigInt((raw[i] % 5) - 2));
    const s2h = negacyclicMul(s2, h.map(BigInt), n);
    const s1 = s2h.map((v, i) => {
      let x = (((BigInt(c[i]) - v) % Q) + Q) % Q;
      if (x > half) x -= Q;
      return x;
    });
    const measured = normSq([...s1, ...s2]);
    if (!best || measured < best.normSq) best = { n, q, nonceHex, s1, s2, normSq: measured };
  }
  return { signature: best!, tries, bestNormSq: best!.normSq, bound: TOY_BOUND_SQ };
}

/** Flip one coefficient of the private completion F — the trapdoor, damaged. */
export function damageTrapdoor(key: TrapdoorKeyPair, index = 0, delta = 1n): TrapdoorKeyPair {
  const F = [...key.F];
  F[index] += delta;
  const damaged = { ...key, F };
  const lhs = ntruEquationLhs(damaged);
  return { ...damaged, equationLhs: lhs, equationHolds: equationHolds(lhs, key.q) };
}
